### ISSUE TITLE
No tag for v0.2.1 on Docker Hub

### ISSUE THREAD

**Issue by imikushin** [rancherio/os-installer#5]
See https://registry.hub.docker.com/u/rancher/os-installer/tags/manage/

Currently there are only these tags: 
`v0.1.1`
`v0.1.2`

**Comment by cloudnautique** [comment]
We dropped the -installer it is just os

**Comment by cloudnautique** [comment]
https://registry.hub.docker.com/u/rancher/os/tags/manage/

**Comment by cloudnautique** [comment]
Sorry for the confusion @imikushin we used that name during development and decided to change it as we went live. I removed the rancher/os-installer repo from docker hub.

Thanks!
